name : Continuous Integration 

# trigger
on:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
  build-and-test:
      name: Build and Test application
      # specify runner enviournment
      runs-on: ubuntu-latest

      steps:
        # step 1 checkout the repo's source code 
        - name: Checkout code
          uses: actions/checkout@v4

        # step 2 set up the runtime enviournment
        - name: Setup enviournment
          uses: actions/setup-python@v5
          with:
            python-version: "3.13.6"

        # step 3 install dependencies
        - name: Install dependencies
          run: pip install -r requirements.txt

        # step 4 execute tests 
        - name: Run tests 
          run: pytest

